version: "3"

services:
  postgres:
    container_name: ualapp_postgres
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
