version: "3.9"
services:
  postgres:
    container_name: ualapp_postgres
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ualapp
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ualapp -U root"]
      interval: 10s
      timeout: 5s
      retries: 3
  api:
    container_name: ualapp_api
    image: ualapp_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/
    depends_on:
      postgres:
        condition: service_healthy
