// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: accounts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO
    accounts (user_id, balance, currency)
VALUES ($1, $2, $3) RETURNING id, user_id, balance, currency, created_at, account_number
`

type CreateAccountParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Balance  int64     `json:"balance"`
	Currency string    `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.UserID, arg.Balance, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.AccountNumber,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const deleteAllAccounts = `-- name: DeleteAllAccounts :exec
DELETE FROM accounts
`

func (q *Queries) DeleteAllAccounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllAccounts)
	return err
}

const getAccountByAccountNumber = `-- name: GetAccountByAccountNumber :one
SELECT accounts.id, accounts.user_id, accounts.balance, accounts.currency, accounts.created_at, accounts.account_number, users.email
FROM accounts
    INNER JOIN users ON accounts.user_id = users.id
WHERE
    account_number = $1
`

type GetAccountByAccountNumberRow struct {
	ID            int32       `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	Balance       int64       `json:"balance"`
	Currency      string      `json:"currency"`
	CreatedAt     time.Time   `json:"created_at"`
	AccountNumber pgtype.Text `json:"account_number"`
	Email         string      `json:"email"`
}

func (q *Queries) GetAccountByAccountNumber(ctx context.Context, accountNumber pgtype.Text) (GetAccountByAccountNumberRow, error) {
	row := q.db.QueryRow(ctx, getAccountByAccountNumber, accountNumber)
	var i GetAccountByAccountNumberRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.AccountNumber,
		&i.Email,
	)
	return i, err
}

const getAccountById = `-- name: GetAccountById :one
SELECT id, user_id, balance, currency, created_at, account_number FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountById(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.AccountNumber,
	)
	return i, err
}

const getAccountsFromUser = `-- name: GetAccountsFromUser :many
SELECT id, user_id, balance, currency, created_at, account_number FROM accounts WHERE user_id = $1
`

func (q *Queries) GetAccountsFromUser(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountsFromUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
			&i.AccountNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, user_id, balance, currency, created_at, account_number FROM accounts ORDER BY id LIMIT $1 OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
			&i.AccountNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET
    balance = balance + $1
WHERE
    id = $2 RETURNING id, user_id, balance, currency, created_at, account_number
`

type UpdateAccountBalanceParams struct {
	Amount int64 `json:"amount"`
	ID     int32 `json:"id"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.Amount, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.AccountNumber,
	)
	return i, err
}

const updateAccountNumber = `-- name: UpdateAccountNumber :one
UPDATE accounts SET account_number = $1 WHERE id = $2 RETURNING id, user_id, balance, currency, created_at, account_number
`

type UpdateAccountNumberParams struct {
	AccountNumber pgtype.Text `json:"account_number"`
	ID            int32       `json:"id"`
}

func (q *Queries) UpdateAccountNumber(ctx context.Context, arg UpdateAccountNumberParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountNumber, arg.AccountNumber, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.AccountNumber,
	)
	return i, err
}
