// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/shopspring/decimal"
)

type Account struct {
	ID        int32           `json:"id"`
	UserID    int32           `json:"user_id"`
	Balance   decimal.Decimal `json:"balance"`
	Currency  string          `json:"currency"`
	CreatedAt time.Time       `json:"created_at"`
}

type Entry struct {
	ID        int32 `json:"id"`
	AccountID int32 `json:"account_id"`
	// can be negative or positive
	Amount    decimal.Decimal `json:"amount"`
	CreatedAt time.Time       `json:"created_at"`
}

type Transfer struct {
	ID            int32 `json:"id"`
	FromAccountID int32 `json:"from_account_id"`
	ToAccountID   int32 `json:"to_account_id"`
	// must be positive
	Amount    float32   `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             int32     `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
